[build]
  # Directory where your site files are located
  publish = "public"
  # Directory for serverless functions
  functions = "functions"

[functions]
  # Specify the Node.js bundler for serverless functions
  node_bundler = "esbuild"

[build.environment]
  # Specify the Node.js version
  NODE_VERSION = "18"

# Optional: Redirect rules (if needed)
[[redirects]]
  from = "/download-outline"
  to = "/.netlify/functions/sendToSlack"
  status = 200
