[build]
  # Remove 'publish' since we are not deploying static files
  functions = "functions"

[functions]
  # Specify the Node.js bundler
  node_bundler = "esbuild"

[build.environment]
  # Specify the Node.js version
  NODE_VERSION = "18"

[[redirects]]
  from = "/download-outline"
  to = "/.netlify/functions/sendToSlack"
  status = 200
